In [1]:
import numpy as np

In [2]:
data1 = [10, 9.9, 9.8, 9.7, 9.6]

In [3]:
data1

[10, 9.9, 9.8, 9.7, 9.6]

In [4]:
arr1 = np.array(data1)

In [5]:
np.array?

In [6]:
arr1

array([ 10. ,   9.9,   9.8,   9.7,   9.6])

In [7]:
arr1.shape

(5,)

In [8]:
np.zeros((3,5)) 

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
np.zeros(5) 

array([ 0.,  0.,  0.,  0.,  0.])

In [10]:
np.ones((2,7)) 

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [11]:
np.ones(5) 

array([ 1.,  1.,  1.,  1.,  1.])

In [12]:
data2 = [ [1,2,3,4], [5,6,7,8]] 

In [13]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int32')

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [19]:
arr.dtype

dtype('int64')

In [20]:
f_arr = arr.astype(np.float64)

In [21]:
f_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [22]:
f_arr.dtype

dtype('float64')

In [23]:
arr1 = np.array([ [1,2,3], [4,5,6]], dtype=np.float64)
arr2 = np.array([ [7,8,9], [10,11,12]], dtype=np.float64)

In [24]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [25]:
arr2

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [26]:
arr1 * arr2

array([[  7.,  16.,  27.],
       [ 40.,  55.,  72.]])

In [27]:
arr1 + arr2

array([[  8.,  10.,  12.],
       [ 14.,  16.,  18.]])

In [28]:
arr1 * 2

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [29]:
names = np.array(["pyo", "sunyoung", "psy", "pyo", "sunyoung", "sunny", "sunyoung"])

In [30]:
data = np.random.randn(7,4) 

In [31]:
names

array(['pyo', 'sunyoung', 'psy', 'pyo', 'sunyoung', 'sunny', 'sunyoung'],
      dtype='<U8')

In [32]:
data

array([[ 1.25747549, -0.23163847,  1.03455154, -1.50494454],
       [ 0.14210188,  1.63564293, -0.8864477 , -0.34988824],
       [ 0.67677943,  0.92236948,  0.76574899,  0.25990345],
       [ 1.61618348,  1.14300848,  1.00659737,  1.40445331],
       [-0.65791583, -0.47669861,  1.56418892, -1.10737826],
       [ 1.55379996,  1.66923212, -0.25893643,  0.67572661],
       [-0.92331183,  0.57874804, -0.01141675, -0.33712098]])

In [33]:
names == "sunyoung"

array([False,  True, False, False,  True, False,  True], dtype=bool)

In [34]:
data[names=="sunyoung" , :] 

array([[ 0.14210188,  1.63564293, -0.8864477 , -0.34988824],
       [-0.65791583, -0.47669861,  1.56418892, -1.10737826],
       [-0.92331183,  0.57874804, -0.01141675, -0.33712098]])

In [35]:
data[names=="pyo" , :] 

array([[ 1.25747549, -0.23163847,  1.03455154, -1.50494454],
       [ 1.61618348,  1.14300848,  1.00659737,  1.40445331]])

In [36]:
data[(names=="pyo") | (names=="sunyoung")] 

array([[ 1.25747549, -0.23163847,  1.03455154, -1.50494454],
       [ 0.14210188,  1.63564293, -0.8864477 , -0.34988824],
       [ 1.61618348,  1.14300848,  1.00659737,  1.40445331],
       [-0.65791583, -0.47669861,  1.56418892, -1.10737826],
       [-0.92331183,  0.57874804, -0.01141675, -0.33712098]])

In [37]:
data[ : ,3]

array([-1.50494454, -0.34988824,  0.25990345,  1.40445331, -1.10737826,
        0.67572661, -0.33712098])

In [38]:
data[ : ,3] < 0

array([ True,  True, False, False,  True, False,  True], dtype=bool)

In [39]:
data[data[ : ,3] < 0 , : ] = 0

In [40]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.67677943,  0.92236948,  0.76574899,  0.25990345],
       [ 1.61618348,  1.14300848,  1.00659737,  1.40445331],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.55379996,  1.66923212, -0.25893643,  0.67572661],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [41]:
a=[1,2]
b=[1,2]
print(a+b)

[1, 2, 1, 2]


In [42]:
c = np.array([1,2])
d = np.array([1,2])
print(c+d)

[2 4]


In [43]:
c = np.array([1,2,3]) 
d = np.array([1,2]) 
print(c+d)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [44]:
(1,2,3)+(1,2,3) 

(1, 2, 3, 1, 2, 3)

In [45]:
(1,2,3)+(1,2,3,4) 

(1, 2, 3, 1, 2, 3, 4)